### ISSUE TITLE
GitHub action on pull_request is not executed

### ISSUE THREAD

**Issue by rachelcarmena** [gr2m/create-or-update-pull-request-action#158]
Hi Gregor @gr2m ,

Thanks so much for this GitHub Action :sparkles: :clap: 

Please, maybe I'm doing something wrong though I don't get that the created pull request works like a manual pull request. I mean, I have a branch protection rule for `master` branch. If I create a pull request manually, the check is executed. It's triggered by:

```
on: pull_request
```

However, with automatic pull requests, the check remains without execution:

![Screenshot from 2019-12-19 15-05-18](https://user-images.githubusercontent.com/22792183/71179732-093f1780-2271-11ea-8776-16e985d2bc02.png)

and I have to push a change to the created branch, for instance:

```
git checkout <branch-created-by-github-action>
git commit --amend
git push -f origin <branch-created-by-github-action>
```

to force that check execution:

![Screenshot from 2019-12-19 14-57-40](https://user-images.githubusercontent.com/22792183/71179608-d137d480-2270-11ea-8072-28a43046d55f.png)

Please, would you have an idea about the reason of that behavior? Can I help you to fix it? 

Maybe it's a prevention of a loop of GitHub Actions execution because the PR was created by a GitHub Action and the protection rule check is another GitHub action. However, they are different GitHub Actions. Or maybe it's necessary to trigger an event...

I had the same problem with https://github.com/peter-evans/create-pull-request. 

Looking forward to having news from you. Thanks in advance!

**Comment by gr2m** [comment]
> Maybe it's a prevention of a loop of GitHub Actions execution because the PR was created by a GitHub Action

Yes, that's it. It makes no difference if the event was triggered by a different action, unfortunately :(

**Comment by rachelcarmena** [comment]
> > Maybe it's a prevention of a loop of GitHub Actions execution because the PR was created by a GitHub Action
> 
> Yes, that's it. It makes no difference if the event was triggered by a different action, unfortunately :(

Thanks for the quick answer @gr2m !! :tada: So I'll add the check (a few lines) before creating the pull request so I know that everything is working as expected when the pull request is created.

And users with admin grants will be able to merge the automatic pull request without checks execution :+1:  Then, all the checks are repeated again when merging on `master` together other tasks.

Thanks again!! :raised_hands: 

Closing... :wink:

**Comment by G-Rath** [comment]
@gr2m this is probably worth putting in the README for visibility - I only just noticed that checks weren't running for the PRs on my repo 😬

**Comment by gr2m** [comment]
good idea, I made a follow up issue here: https://github.com/gr2m/create-or-update-pull-request-action/issues/281
