### ISSUE TITLE
Updating a pull request fails: Command failed with exit code 128

### ISSUE THREAD

**Issue by vadi2** [gr2m/create-or-update-pull-request-action#177]
Hi!

Updating a remote branch seems to fail if it exists already - see [run1](https://github.com/Mudlet/Mudlet/actions/runs/55498515) where it was created successfully and [run2](https://github.com/Mudlet/Mudlet/runs/507423448?check_suite_focus=true) where updating it failed with:

```
Remote branch "update-texts-for-translators" checked out locally.
Branch "update-texts-for-translators" does not yet exist on remote.
##[error]Command failed with exit code 128 (Unknown system error -128): git checkout -b update-texts-for-translators
```

What could be wrong?

**Comment by gr2m** [comment]
I'm sorry I don't know out of my head, and I can't look into it right now I'm afraid. The git operations are somewhat complicated, I'm very open to suggestions how to make it more resilient.

**Comment by Perksey** [comment]
Can reproduce https://github.com/Ultz/Silk.NET/runs/1072486960

**Comment by gr2m** [comment]
I'd still appreciate help with debugging and fixing this issue

**Comment by bnb** [comment]
Also hitting this, though it's on PR creation - just came here to report it. Specifically seems to be happening when using the `branch` property in the config - things seem to go as expected without that.

Here's an example run: https://github.com/bnb/node/runs/1327432876?check_suite_focus=true
