### ISSUE TITLE
Error using v1.9.0

### ISSUE THREAD

**Issue by armrib** [gr2m/create-or-update-pull-request-action#500]
This is the problem with v1.9.0, I cannot use v1.5.1 because I need some features from your new tag.

>Run grm/create-or-update-pull-request-action@v1.9.0
with:
title: Automatic bump of ##### to version 2022.2.11
 body: Update report
    -Bump ##### to 2022.2.11
    -Auto-generated by [create-or-update-pull-request-action][1]
[1]: https://github.com/gr2m/create-or-update-pull-request-action
 branch: 2-test
 path: .
 commit-message: chore: Auto bump ##### to version 2022.2.11
 author: GitHub Actions <no-reply@github.com>
 reviewers: armrib
 auto-merge: squash
 update-pull-request-title-and-body: false

Error: File not found: '/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.9.0/dist/index.js'

Any idea why ? 
Maybe the release is incorrect or v1.9.0 is not available in the marketplace yet ?
Also, would it be possible in the README to describe all params and default please ?
Thank you for this very nice plugin btw !

**Comment by armrib** [comment]
Using v1.x seems to work, I'll use it.

**Comment by gr2m** [comment]
`v1.9.0` does not have the `dist/` files, but they do exist in `v1.x`
