### ISSUE TITLE
Cut a release tag

### ISSUE THREAD

**Issue by mraerino** [gr2m/create-or-update-pull-request-action#530]
The most recent release tag is from Dec 2021. Would you be able to cut a newer release so we can use that instead of referring to the action via the commit sha?

If you want to get sophisticated you could also configure [release please](https://github.com/googleapis/release-please) to automate the versioning

**Comment by gr2m** [comment]
I do have release automation setup:
https://github.com/gr2m/create-or-update-pull-request-action/blob/master/.github/workflows/release.yml

The last commit that needed a release was from Dec 2021: 
https://github.com/gr2m/create-or-update-pull-request-action/commits/master

Anything you miss in particular?

**Comment by mraerino** [comment]
oh sorry, i missed that nothing relevant was committed since then. the tag just seemed a little old. all good.
