### ISSUE TITLE
Can I turn off the rebase behavior?

### ISSUE THREAD

**Issue by AArnott** [gr2m/create-or-update-pull-request-action#712]
From your doc:

> If a pull request exists for the branch, it's checked out locally, rebased with -XTheirs and pushed with --force to update the pull request with the new changes.

This would be intolerable for my use case. If the PR already exists, I'd rather just force push my topic branch over top of it or not push at all. Rebase would wreck what I'm doing. Can I turn it off?

**Comment by gr2m** [comment]
I don't think so, but there are actions out there that work different
